#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/{keys,php,www} \
    /config/log/{nginx,php,simplesamlphp} \
    /config/nginx \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx \
    /tmp/simplesamlphp